# -*- coding: utf-8 -*-
"""w266_final_project_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14AFVOjgj-lyPTySxe98s4FnII8iNjkKH
"""

!pip install datasets

from datasets import load_dataset

dataset = load_dataset("gretelai/symptom_to_diagnosis")

dataset

train_texts, test_texts, train_labels, test_labels = dataset.['train']['input_text'],dataset.['test']['input_text'],dataset.['train']['output_text'],dataset.['test']['output_text']

possible_labels = train_labels.output_text.unique()

label_dict = {}
for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index
label_dict

!pip install -q transformers

!pip install pydot

from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from collections import Counter
import numpy as np
import tensorflow as tf
from tensorflow import keras

import seaborn as sns
import matplotlib.pyplot as plt
from pprint import pprint

from transformers import BertTokenizer, TFBertModel

len(test_texts)

valid_texts = train_texts[:108].to_list()
valid_labels = train_labels[:108].to_numpy()
train_texts = train_texts[108:].to_list()
train_labels = train_labels[108:].to_numpy()
test_texts = test_texts.to_list()
test_labels = test_labels.to_numpy()

def labels_to_int(data):
  out = []
  for lable in data:
    out.append(label_dict[lable])
  return out

train_labels = labels_to_int(train_labels)
test_labels = labels_to_int(test_labels)
valid_labels = labels_to_int(valid_labels)

npvalid_labels = np.asarray(valid_labels)
train_labels = np.asarray(train_labels)
test_labels = np.asarray(test_labels)
valid_labels = np.asarray(valid_labels)

#make it easier to use a variety of BERT subword models
model_checkpoint = 'bert-base-cased'

bert_tokenizer = BertTokenizer.from_pretrained(model_checkpoint)
bert_model = TFBertModel.from_pretrained(model_checkpoint)

max_length = 200

# tokenize the dataset, truncate at `max_length`,
# and pad with 0's when less than `max_length` and return a tf Tensor
train_encodings = bert_tokenizer(train_texts, truncation=True, padding='max_length', max_length=200, return_tensors='tf')
valid_encodings = bert_tokenizer(valid_texts, truncation=True, padding='max_length', max_length=200, return_tensors='tf')
test_encodings = bert_tokenizer(test_texts, truncation=True, padding='max_length', max_length=200, return_tensors='tf')

train_encodings.input_ids[:1]

def create_bert_multiclass_model(checkpoint = model_checkpoint,
                                 num_classes = 24,
                                 hidden_size = 80,
                                 dropout=0.3,
                                 learning_rate=0.00005):
    """
    Build a simple classification model with BERT. Use the Pooler Output for classification purposes.
    """
    ### YOUR CODE HERE
    bert_model.trainable = True

    input_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='input_ids_layer')
    token_type_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='token_type_ids_layer')
    attention_mask = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='attention_mask_layer')

    bert_inputs = {'input_ids': input_ids,
                   'token_type_ids': token_type_ids,
                   'attention_mask': attention_mask}

    bert_out = bert_model(bert_inputs)

    pooler_token = bert_out[1]

    hidden = tf.keras.layers.Dense(hidden_size, activation='relu', name='hidden_layer')(pooler_token)


    hidden = tf.keras.layers.Dropout(dropout)(hidden)


    classification = tf.keras.layers.Dense(num_classes, activation='softmax',name='classification_layer')(hidden)

    classification_model = tf.keras.Model(inputs=[input_ids, token_type_ids, attention_mask], outputs=[classification])

    classification_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                                 loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
                                 metrics='accuracy')

    ### END YOUR CODE
    return classification_model

pooler_bert_model = create_bert_multiclass_model(checkpoint=model_checkpoint, num_classes=24)

pooler_bert_model.summary()

keras.utils.plot_model(pooler_bert_model, show_shapes=False, show_dtype=False, show_layer_names=True, dpi=90)

pooler_bert_model_history = pooler_bert_model.fit([train_encodings.input_ids, train_encodings.token_type_ids, train_encodings.attention_mask],
                                                  train_labels,
                                                  validation_data=([valid_encodings.input_ids, valid_encodings.token_type_ids, valid_encodings.attention_mask],
                                                  npvalid_labels),
                                                  batch_size=8,
                                                  epochs=10)

score = pooler_bert_model.evaluate([test_encodings.input_ids, test_encodings.token_type_ids, test_encodings.attention_mask],
                                                  test_labels)

print('Test loss:', score[0])
print('Test accuracy:', score[1])

predictions = pooler_bert_model.predict([test_encodings.input_ids[:3], test_encodings.token_type_ids[:3], test_encodings.attention_mask[:3]])



predictions

#run and capture all predictions from our test set using model.predict
### YOUR CODE HERE
predictions_model1 = pooler_bert_model.predict([test_encodings.input_ids, test_encodings.token_type_ids, test_encodings.attention_mask])
### END YOUR CODE

#now we need to get the highest probability in the distribution for each prediction
#and store that in a tf.Tensor
predictions_model1 = tf.argmax(predictions_model1, axis=-1)
predictions_model1

print(classification_report(test_labels, predictions_model1.numpy(), target_names=list(label_dict.keys())))

cm = tf.math.confusion_matrix(test_labels, predictions_model1)
cm = cm/cm.numpy().sum(axis=1)[:, tf.newaxis]

plt.figure(figsize=(20,7))
sns.heatmap(
    cm, annot=True,
    xticklabels=list(label_dict.keys()),
    yticklabels=list(label_dict.keys()))
plt.xlabel("Predicted")
plt.ylabel("True")

from matplotlib import pyplot as plt
plt.plot(pooler_bert_model_history.history['accuracy'])
plt.plot(pooler_bert_model_history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

plt.plot(pooler_bert_model_history.history['loss'])
plt.plot(pooler_bert_model_history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

"""## Knowledge Graph and BERT"""

# Commented out IPython magic to ensure Python compatibility.
import re
import pandas as pd
import bs4
import requests
import spacy
from spacy import displacy
nlp = spacy.load('en_core_web_sm')

from spacy.matcher import Matcher
from spacy.tokens import Span

import networkx as nx

import matplotlib.pyplot as plt
from tqdm import tqdm

pd.set_option('display.max_colwidth', 200)
# %matplotlib inline

data = pd.read_csv('/content/dataset.csv')
data.head(5)
# kg_df = pd.DataFrame({'source':source, 'target':target, 'edge':relations})

diseases = data['Disease'].unique()
diseases

final = set()
for disease in diseases:
  new = set(data[data['Disease']==disease].drop('Disease',axis=1).values.flatten())
  for symp in new:
    symp = str(symp).strip()
    if symp == 'nan':
      continue
    if " _" in symp:
      symp = symp.replace(" _"," ")
    elif "_" in symp:
      symp = symp.replace("_"," ")
    final.add((str(symp).strip(),str(disease)))
sources = [node[0] for node in final]
targets = [node[1] for node in final]

nodal_df = pd.DataFrame({'source':sources,'target':targets,'edge':'symptom of'})
#malaria = nodal_df[nodal_df['target'] == 'Malaria']

G=nx.from_pandas_edgelist(nodal_df, "source", "target",
                          edge_attr=True, create_using=nx.MultiDiGraph())

adj = nx.adjacency_matrix(G)
adj.shape

len(G.nodes())

len(set(sources)) + len(set(diseases))

plt.figure(figsize=(12,12))

pos = nx.spring_layout(G)
nx.draw(G, with_labels=True, node_color='skyblue', edge_cmap=plt.cm.Blues, pos = pos)
plt.show()

from keras.models import Model
from keras.layers import Input, Dropout, Dense
from keras.optimizers import Adam
from spektral.layers import *

# Assuming you have the 'spektral' library installed (can be installed via pip install spektral)

# Create an adjacency matrix (adjacency_matrix) and node features (node_features)
# These are just placeholder values - you should replace them with your actual data

# Placeholder values
num_nodes = len(G.nodes())
num_features = 172
num_classes = len(diseases)

# Define the adjacency matrix (for simplicity, assuming an undirected graph)
adjacency_matrix = nx.adjacency_matrix(G)
  # Your adjacency matrix here

# Define node features
node_features = np.array([G.degree[node] for node in G.nodes()])  # Your node features here

# Input layer
X_in = Input(shape=(num_features,))

# Graph Convolutional Network (GCN) layer
graph_conv1 = GraphConv(32, activation='relu')([X_in, adjacency_matrix])

# Dropout for regularization
dropout = Dropout(0.5)(graph_conv1)

# Fully connected layer for classification
output_layer = Dense(num_classes, activation='softmax')(dropout)

# Create and compile the model
model = Model(inputs=X_in, outputs=output_layer)
model.compile(optimizer=Adam(lr=0.01), loss='categorical_crossentropy', metrics=['accuracy'])

# Print a summary of the model architecture
model.summary()

# Assuming you have node labels for a node classification task
labels = [i for i in range(len(diseases))]  # Your node labels here (one-hot encoded for multi-class classification)

# Train the model
model.fit(node_features, labels, epochs=100, batch_size=1)

!pip install spektral

import pandas as pd
df_train=pd.DataFrame(data=dataset['train'])
df_train.head()

df_train.output_text.unique()

sorted_df = df_train.sort_values('output_text')

possible_labels = sorted_df.output_text.unique()

label_dict = {}
for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index
label_dict

df_test=pd.DataFrame(data=dataset['test'])
len(df_test['output_text'].unique())

df_test.count() + df_train.count()

knowledge_graph = list(sorted_df.set_index('input_text').to_dict().values())[0]
answers = list(knowledge_graph.values())
labelled_graph = {}
for key,value in knowledge_graph.items():
  labelled_graph[key] = label_dict[value]

answers = list(labelled_graph.values())
answers

import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense
from tensorflow.keras.models import Model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Sample data (replace this with your knowledge graph and Q&A pairs)
knowledge_graph = labelled_graph

# Preprocess data
questions = list(knowledge_graph.keys())
answers = list(knowledge_graph.values())

# Tokenize and vectorize questions using TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(questions)

# Function to get the most similar question from the knowledge graph
def get_most_similar_question(query):
    query_vector = vectorizer.transform([query])
    similarities = cosine_similarity(query_vector, X).flatten()
    most_similar_index = similarities.argmax()
    return questions[most_similar_index]

# Neural Network for generating responses
input_layer = Input(shape=(len(questions),))
embedding_layer = Embedding(input_dim=len(questions), output_dim=50)(input_layer)
lstm_layer = LSTM(100)(embedding_layer)
output_layer = Dense(len(answers), activation="softmax")(lstm_layer)

model = Model(inputs=input_layer, outputs=output_layer)
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
print(model.summary())
# Dummy labels for training (replace this with a more meaningful setup)
labels = np.asarray(answers)

# Train the model (replace this with a more meaningful setup)
model.fit(X, labels, epochs=10, batch_size=8, shuffle=True)

# Function to get a response from the neural network
# def get_nn_response(query):
#     query_index = questions.index(get_most_similar_question(query))
#     query_vector = vectorizer.transform([query])
#     return model.predict(query_vector)[0]

# # Example usage
# user_query = "What is Python programming language?"
# most_similar_question = get_most_similar_question(user_query)
# nn_response = get_nn_response(user_query)

# print("Most similar question from knowledge graph:", most_similar_question)
# print("Neural network response:", answers[nn_response.argmax()])

